from typing import Protocol
from .message_tasks import MessageTask


class MessagePublisherInterface(Protocol):
    async def connect(self): ...
    async def disconnect(self): ...

    async def publish(self, task: MessageTask): ...
