from typing import Protocol, Optional, Any, Sequence

from src.domain.entities import Course, Module


class CourseRepositoryInterface(Protocol):
    async def get_by_id(self, course_id: int) -> Optional[Course]: ...
    async def get_all_paginated(
        self, page: int = 0, size: int = 10) -> tuple[list[Course], int, int, int]: ...

    async def get_student_courses(self, student_id: int) -> list[Course]: ...
    async def get_teacher_courses(self, teacher_id: int) -> list[Course]: ...

    async def get_by_id_with_rels(self, course_id: int, *
                                  rels_chains: Sequence[Any]) -> Optional[Course]: ...

    async def check_user_in_course(self, user_id: int, course_id: int) -> bool: ...
