from typing import Protocol, Optional, Any

from src.domain.entities import Course, Module


class CourseRepositoryInterface(Protocol):
    async def get_by_id(self, course_id: int) -> Optional[Course]: ...
    async def get_user_courses(self, user_id: int) -> list[Course]: ...
    async def get_by_id_with_rels(self, course_id: int, *rels: Any) -> Optional[Course]: ...

    async def get_by_id_to_manage_students(seld, course_id: int) -> Optional[Course]:
        """
        Returns course with loaded students, tags and loaded tags students
        """

    async def get_by_id_for_students(self, course_id: int) -> Optional[Course]: ...
    async def get_course_full_rels(self, course_id: int) -> Optional[Course]: ...
    async def check_user_in_course(self, user_id: int, course_id: int) -> bool: ...
