from typing import Protocol, Optional

from domain.entities import User


class UserRepositoryInterface(Protocol):
    async def get_by_id(self, user_id: int) -> Optional[User]: ...
    async def get_by_email(self, email: str) -> Optional[User]: ...
    async def count_by_email(self, email: str) -> int: ...
    async def create(self, name: str, email: str, password: str) -> User: ...
