from typing import Protocol, Optional

from runlet.domain.entities import User


class UserRepositoryInterface(Protocol):
    async def get_by_id(self, user_id: int) -> Optional[User]: ...
    async def get_by_ids(self, user_ids: list[int]) -> list[User]: ...
    async def get_by_email(self, email: str) -> Optional[User]: ...
    async def count_by_email(self, email: str) -> int: ...
    async def find_by_name(self, course_id: int, namelike: str, tag_id: Optional[int] = None) -> list[User]: ...

    async def get_by_id_with_attempts_seen_info(
        self,
        course_id: int,
    ) -> list[tuple[User, bool]]: ...
