from typing import Protocol, Optional


class AuthenticationServiceInterface(Protocol):
    def generate_token(self, user_id: int, exp: Optional[int] = None) -> str: ...
    def get_user_id_from_token(self, token: str) -> Optional[int]: ...
